services:
  seamless-api:
    container_name: seamless-api-local
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        CUSTOM_REGISTRY: https://registry.npmmirror.com
    image: seamless-api-local
    env_file:
      - .env.docker
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm start:dev
    networks:
      - seamless-network

  db:
    image: postgres:16
    container_name: seamless-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: seamless
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: 'UTC'
    ports:
      - '25432:5432'
    networks:
      - seamless-network

  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
    environment:
      REDIS_ARGS: '--requirepass redispass'
    networks:
      - seamless-network

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025
    networks:
      - seamless-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '18080:80'
    volumes:
      - pgadmin_data:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
    networks:
      - seamless-network

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:

networks:
  seamless-network:
    driver: bridge
